# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:


# It can be verified that T285 = P165 = H143 = 40755

# Find the next triangle number that is also pentagonal and hexagonal.

# Answer = 1533776805

T = set()
for i in range(300000):
    T.add(i * (i + 1) / 2)
P = set()
for i in range(400000):
    P.add(i * (3 * i - 1) / 2)
H = set()
for i in range(500000):
    H.add(i * (2 * i - 1))

print(T & P & H)
