"""
PROBLEM

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be
1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

ANSWER: 76576500
Solve time: ~0.019 seconds
"""

import unittest
from util.utils import timeit, num_of_divisors


class Problem12:
    def __init__(self, min_divisors):
        self.min_divisors = min_divisors

    @timeit
    def solve(self):
        n = 1
        while True:
            # triangle(1) = 1 has no prime factors, so num_of_divisors would fail. Start counting from triangle(2).
            n += 1
            triangle = n * (n + 1) // 2
            if num_of_divisors(triangle) > self.min_divisors:
                return triangle


class Solution12(unittest.TestCase):
    def setUp(self):
        self.problem = Problem12(500)

    def test_solution(self):
        self.assertEqual(76576500, self.problem.solve())


if __name__ == '__main__':
    unittest.main()
