"""
PROBLEM

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
Starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Every positive integer can be uniquely written as a sum of non-consecutive terms of the Fibonacci sequence.
For example, 100 = 89 + 8 + 3.
This is known as the Zeckendorf's theorem and the relation is called the Zeckendorf representation of the number.

For any integer n>0, let z(n) be the number of terms in the Zeckendorf representation of n.
Thus, z(5) = 1, z(14) = 2, z(100) = 3 etc.
Also, for 0 < n < 10^6, sum(z(n)) = 7894453.

Find sum(z(n)) for 0 < n < 10^17.

ANSWER: 2252639041804718029
Solve time: ~0.001 seconds
"""

import bisect
from functools import lru_cache
import unittest
from util.utils import timeit


class Problem297:
    def __init__(self, limit: int):
        self.limit = limit
        self.fibs = [1, 2]
        while True:
            nxt = self.fibs[-1] + self.fibs[-2]
            if nxt > self.limit:
                break
            self.fibs.append(nxt)

        # f[k] is sum_{x=1}^{F_k - 1} z(x) where F_k = self.fibs[k - 1] (1-indexed)
        # f[1] = 0 (for F_1 = 1)
        # f[2] = 1 (for F_2 = 2)
        # f[k] = f[k-1] + F_{k-2} + f[k-2]
        self.f = [0] * (len(self.fibs) + 1)
        self.f[1] = 0
        if len(self.fibs) >= 2:
            self.f[2] = 1
        for k in range(3, len(self.fibs) + 1):
            self.f[k] = self.f[k - 1] + self.fibs[k - 3] + self.f[k - 2]

    @lru_cache(maxsize=None)
    def count_terms(self, n: int) -> int:
        """Computes sum_{x=1}^{n-1} z(x)."""
        if n <= 1:
            return 0

        idx = bisect.bisect_right(self.fibs, n)
        k = idx  # 1-indexed Fibonacci term index
        f_k = self.fibs[k - 1]

        if n == f_k:
            return self.f[k]

        return self.f[k] + (n - f_k) + self.count_terms(n - f_k)

    @timeit
    def solve(self) -> int:
        return self.count_terms(self.limit)


class Solution297(unittest.TestCase):
    def setUp(self):
        self.problem_small = Problem297(limit=10**6)
        self.problem = Problem297(limit=10**17)

    def test_small(self):
        self.assertEqual(7894453, self.problem_small.solve())

    def test_solution(self):
        self.assertEqual(2252639041804718029, self.problem.solve())


if __name__ == '__main__':
    unittest.main()
