r"""
PROBLEM

$(x,y)$ is called a nested radical pair if $x$ and $y$ are non-zero integers such that $\dfrac{x}{y}$ is not a cube of a rational number, and there exist integers $a$, $b$ and $c$ such that:

$$\sqrt{\sqrt[3]{x}+\sqrt[3]{y}}=\sqrt[3]{a}+\sqrt[3]{b}+\sqrt[3]{c}$$

For example, both $(-4,125)$ and $(5,5324)$ are nested radical pairs:

$$
\begin{align*}
\begin{split}
\sqrt{\sqrt[3]{-4}+\sqrt[3]{125}}	&= \sqrt[3]{-1}+\sqrt[3]{2}+\sqrt[3]{4}\\
\sqrt{\sqrt[3]{5}+\sqrt[3]{5324}}	&= \sqrt[3]{-2}+\sqrt[3]{20}+\sqrt[3]{25}\\
\end{split}
\end{align*}
$$

Let $H(N)$ be the sum of $|x|+|y|$ for all the nested radical pairs $(x, y)$ where $|x| \leq |y|\leq N$.

For example, $H(10^3)=2535$.

Find $H(10^{15})$. Give your answer modulo $1031^3+2$.

ANSWER: 522095328
Solve time: ~10.5 seconds

---
MATHEMATICAL DERIVATION:

1. Ramanujan's Cubic Nested Radical Identity:
   The denesting of cubic radicals of the form $\sqrt{\sqrt[3]{x} + \sqrt[3]{y}} = \sqrt[3]{a} + \sqrt[3]{b} + \sqrt[3]{c}$
   originates from Ramanujan's Notebooks (Part IV, Chapter 22, Entry 4; see also B. C. Berndt and S. Landau, 1994).

   Let $S = \sqrt[3]{u} + \sqrt[3]{v} + \sqrt[3]{w}$ with $u + v + w = 0$.
   Squaring $S$ yields:
   $$S^2 = (u^{2/3} + v^{2/3} + w^{2/3}) + 2(u^{1/3}v^{1/3} + u^{1/3}w^{1/3} + v^{1/3}w^{1/3})$$
   Using the algebraic identity $(u^{1/3} + v^{1/3} + w^{1/3})^3 = u + v + w + 3(u^{1/3}+v^{1/3})(v^{1/3}+w^{1/3})(w^{1/3}+u^{1/3})$,
   and noting that $(u^{1/3}+v^{1/3})(v^{1/3}+w^{1/3})(w^{1/3}+u^{1/3}) = (S - w^{1/3})(S - u^{1/3})(S - v^{1/3})$,
   when $uvw = r^3$ is a rational cube, the cross terms collapse into a sum of two cube roots:
   $$S^2 = \sqrt[3]{X} + \sqrt[3]{Y}$$

2. Parametrization of Primitive Seeds:
   Setting $u = b/4$, $v = a$, $w = -(a + b/4)$ leads directly to the two-parameter family:
   $$X = b(b + 4a)^3, \qquad Y = 4a(a - 2b)^3$$
   where $a, b > 0$, $\gcd(a, b) = 1$, and $a \ne 2b$ (since $x, y \ne 0$).

3. Parity Split & Coprime Canonical Representatives:
   To ensure all primitive integer solutions are counted exactly once without missing fractional reductions:
   - **Branch 1 (Odd $b$):**
     If $b$ is odd, $(X, Y)$ is already in minimal integer form:
     $$X = b(b + 4a)^3, \qquad Y = 4a(a - 2b)^3$$
     Condition: $\gcd(a, b) = 1$, $a > 0$, $b > 0$ odd.

   - **Branch 2 (Even $b$):**
     If $b$ is even, $b = 2k$. Then $X = 2k(2k + 4a)^3 = 16k(k + 2a)^3$ and $Y = 4a(a - 4k)^3$.
     Both $X$ and $Y$ share a common square factor $4 = 2^2$. Dividing out $4$ gives integer coordinates:
     $$X' = \frac{X}{4} = 2b\left(\frac{b}{2} + 2a\right)^3, \qquad Y' = \frac{Y}{4} = a(a - 2b)^3$$
     Since $\gcd(a, b) = 1$ and $b$ is even, $a$ must be odd.
     Condition: $\gcd(a, b) = 1$, $a > 0$ odd, $b > 0$ even.

4. Multipliers:
   Every valid pair $(x, y)$ is generated by scaling a primitive seed $(X, Y)$ by a square multiplier $t^2$:
   $$(x, y) = (t^2 X, t^2 Y), \qquad 1 \le t \le t_{\max} = \left\lfloor \sqrt{\frac{N}{\max(|X|, |Y|)}} \right\rfloor$$
   The sum of $(|x| + |y|)$ across all valid $t$ is:
   $$(|X| + |Y|) \sum_{t=1}^{t_{\max}} t^2 = (|X| + |Y|) \cdot \frac{t_{\max}(t_{\max} + 1)(2t_{\max} + 1)}{6}$$

5. Rational Cube Exclusion Filter:
   The problem requires that $x/y$ is not a rational cube.
   - For Branch 1: $X/Y = \frac{b(b+4a)^3}{4a(a-2b)^3}$ is a rational cube $\iff \operatorname{cf}(b) = \operatorname{cf}(4a)$.
   - For Branch 2: $X'/Y' = \frac{2b(b/2+2a)^3}{a(a-2b)^3}$ is a rational cube $\iff \operatorname{cf}(2b) = \operatorname{cf}(a)$.
   Here $\operatorname{cf}(n) = \prod_p p^{v_p(n) \bmod 3}$ is the cube-free kernel of $n$, precomputed efficiently via a linear smallest prime factor (SPF) sieve.

6. Search Bounds and Complexity:
   - Sieve limit: $\max(4a, 2b) \le O(N^{1/3}) \approx 4 \times 10^4$.
   - $b$-range: $b \le (4N)^{1/4} \approx 7952$.
   - $a$-range for a given $b$: $a \le \frac{(N/b)^{1/3} - b}{4}$.
   - Total number of pair evaluations is $\int_1^{(4N)^{1/4}} \frac{N^{1/3}}{4 b^{1/3}} db = O(N^{3/8}) \approx 3 \times 10^6$ operations.
   - Overall run time is ~10.5 seconds in pure Python.

REFERENCES:
- S. Landau, "How to Tangle with a Nested Radical", The Mathematical Intelligencer 16(2), pp. 49-55 (1994).
- B. C. Berndt, "Ramanujan's Notebooks, Part IV", Springer-Verlag, Chapter 22.
- Project Euler Thread 880 (discussions by Ecnerwala, hos-lyric, Golovanov399).
"""

import math
import unittest
from util.utils import timeit


class Problem880:
    def __init__(self):
        pass

    @staticmethod
    def _icbrt(n: int) -> int:
        """Floor integer cube root for n >= 0."""
        if n <= 1:
            return n
        r = int(round(n ** (1.0 / 3.0)))
        while (r + 1) ** 3 <= n:
            r += 1
        while r**3 > n:
            r -= 1
        return r

    @staticmethod
    def _iroot4(n: int) -> int:
        """Floor integer fourth root for n >= 0."""
        r = math.isqrt(math.isqrt(n))
        while (r + 1) ** 4 <= n:
            r += 1
        while r**4 > n:
            r -= 1
        return r

    @staticmethod
    def _cube_free_table(limit: int) -> list[int]:
        """Return cf[n] = product p^(v_p(n) mod 3) for 0 <= n <= limit."""
        spf = list(range(limit + 1))
        if limit >= 1:
            spf[1] = 1

        for p in range(2, math.isqrt(limit) + 1):
            if spf[p] != p:
                continue
            for m in range(p * p, limit + 1, p):
                if spf[m] == m:
                    spf[m] = p

        cf = [1] * (limit + 1)
        for n in range(2, limit + 1):
            p = spf[n]
            m = n // p
            e = 1
            while m % p == 0:
                m //= p
                e += 1

            rem = e % 3
            if rem == 0:
                cf[n] = cf[m]
            elif rem == 1:
                cf[n] = cf[m] * p
            else:
                cf[n] = cf[m] * p * p
        return cf

    @staticmethod
    def _sumsq(k: int) -> int:
        """1^2 + 2^2 + ... + k^2."""
        return k * (k + 1) * (2 * k + 1) // 6

    @timeit
    def solve(self, N: int = 10**15, mod: int = 1031**3 + 2) -> int:
        b_limit = self._iroot4(4 * N)

        max_odd_a = max(0, (self._icbrt(N) - 1) // 4)
        max_even_a = max(0, (self._icbrt(N // 4) - 1) // 2)
        cf_limit = max(4 * max_odd_a, max_even_a, 2 * b_limit)
        cf = self._cube_free_table(cf_limit)
        cf4 = [0] * (max_odd_a + 1)
        for a in range(1, max_odd_a + 1):
            cf4[a] = cf[4 * a]

        total = 0
        gcd = math.gcd
        isqrt = math.isqrt
        icbrt_local = self._icbrt
        sumsq_local = self._sumsq

        # Branch 1: Odd b
        for b in range(1, b_limit + 1, 2):
            a_limit = (icbrt_local(N // b) - b) // 4
            cf_b = cf[b]
            for a in range(1, a_limit + 1):
                if gcd(a, b) != 1 or cf_b == cf4[a]:
                    continue

                x_base = b + 4 * a
                x = b * x_base * x_base * x_base
                y_base = a - 2 * b
                y_abs = abs(4 * a * y_base * y_base * y_base)
                max_coord = x if x >= y_abs else y_abs
                if max_coord > N:
                    continue

                tmax = isqrt(N // max_coord)
                total = (total + (x + y_abs) * sumsq_local(tmax)) % mod

        # Branch 2: Even b (a must be odd for gcd(a, b) == 1)
        for b in range(2, b_limit + 1, 2):
            half_b = b // 2
            a_limit = (icbrt_local(N // (2 * b)) - half_b) // 2
            cf_2b = cf[2 * b]
            for a in range(1, a_limit + 1, 2):
                if gcd(a, b) != 1 or cf_2b == cf[a]:
                    continue

                x_base = half_b + 2 * a
                x = 2 * b * x_base * x_base * x_base
                y_base = a - 2 * b
                y_abs = abs(a * y_base * y_base * y_base)
                max_coord = x if x >= y_abs else y_abs
                if max_coord > N:
                    continue

                tmax = isqrt(N // max_coord)
                total = (total + (x + y_abs) * sumsq_local(tmax)) % mod

        return total


class Solution880(unittest.TestCase):
    def setUp(self):
        self.problem = Problem880()

    def test_sample_1000(self):
        self.assertEqual(2535, self.problem.solve(10**3))

    def test_sample_10000(self):
        self.assertEqual(192635, self.problem.solve(10**4))

    def test_sample_100000(self):
        self.assertEqual(9899943, self.problem.solve(10**5))

    def test_solution(self):
        self.assertEqual(522095328, self.problem.solve())


if __name__ == '__main__':
    unittest.main()
