"""
PROBLEM

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj|
is minimised; what is the value of D?

ANSWER:
5482660
Solve time ~0.8 seconds
"""

# p(n) = n(3n−1)/2

# testing if a number is a pentagonal number:
# n = (3x^2 - x)/2
# 3/2 x^2 - 1/2 x - n = 0
# x^2 - 1/3 x - 2/3 n = 0
# x = (1/3 +/- (1/3)*sqrt(1 + 24*n))/2
# x = 1/6 *(1 + sqrt(1 + 24*n))

# if p(n) + p(m) = p(k), m > n
# n(3n−1)/2 + m(3m−1)/2 = (3n^2-n + 3m^2-m)/2 = k(3k−1)/2
# 3n^2 + 3m^2 - m - n = 3k^2 - k
# if p(m) - p(m) = p(q)
# m(3m−1)/2 - n(3n−1)/2 = (3m^2-m - 3n^2-n)/2 = q(3q−1)/2
# 3m^2 - 3n^2 + n - m = 3q^2 - q

from util.utils import timeit
import unittest


class Problem44:
    def __init__(self, max_pentagonal_sum, max_pentagonal_number):
        self.max_pentagonal_sum = max_pentagonal_sum
        self.max_pentagonal_number = max_pentagonal_number
        self.ans = 100000000

    @timeit
    def generate_ls_pentagonal_numbers(self):
        return [int(i * (3 * i - 1) / 2) for i in range(1, self.max_pentagonal_sum)]

    @timeit
    def solve(self):
        ls_pentagonal_numbers = self.generate_ls_pentagonal_numbers()
        set_pentagonal_numbers = set(ls_pentagonal_numbers)
        for m in range(1, self.max_pentagonal_number):
            for n in range(m + 1, self.max_pentagonal_number):
                pent_sum = ls_pentagonal_numbers[m] + ls_pentagonal_numbers[n]
                if pent_sum in set_pentagonal_numbers:
                    pent_diff = ls_pentagonal_numbers[n] - ls_pentagonal_numbers[m]
                    if pent_diff in set_pentagonal_numbers:
                        print(m, n, ls_pentagonal_numbers[m], ls_pentagonal_numbers[n], pent_diff)
                        self.ans = min(pent_diff, self.ans)
        return self.ans


class Solution44(unittest.TestCase):
    def setUp(self):
        self.problem = Problem44(max_pentagonal_sum=10000, max_pentagonal_number=3000)

    def test_solution(self):
        self.assertEqual(5482660, self.problem.solve())


if __name__ == '__main__':
    unittest.main()
